### ISSUE TITLE
Invalid file error while uploading different file format in personal Information admin page.

### ISSUE THREAD

**Issue by aryan7081** [plone/plone.app.users#122]
**Description.**

When attempting to upload an SVG (Scalable Vector Graphics) icon as a portrait in the personal information section via the admin page and clicking on the edit button, an error is encountered instead of the expected behavior of displaying a message indicating that the file format is not supported.

**Steps to reproduce the behavior:**

1. Navigate to the admin page.
2. Click on the "Edit" button in the personal information section.
3. In the form that appears, locate the portrait upload field.
4. Attempt to upload an SVG icon file.
5. Observe the error message instead of the expected notification about unsupported file format.

**Expected Behavior:**
When attempting to upload an invalid file format as a portrait, the system should display a message indicating that the file format is not supported, rather than throwing an error.

**Screenshots**

![Image 14-02-24 at 9 12 PM](https://github.com/plone/volto/assets/71966131/95e2a390-e0eb-48e9-ab8d-382eb814cb77)

**Software (please complete the following information):**

- OS: Mac OS M2
- Browser: Chrome
- Volto Version: 18.0.0-alpha.10
- Plone Version 5.2.2
- Plone REST API Version e.g. 7.0.1

**Additional context**

- Providing proper feedback about unsupported file formats can enhance user experience and prevent confusion.
- Possible solutions may include implementing file format validation or updating error handling to provide clearer messaging to users.

**Comment by stevepiercy** [comment]
## Option 4

I think Plone should accept an SVG for profile images, as some people use SVG icons, not JPG photos.

I thank that Plone should not attempt to resize an SVG through Pillow because its name itself implies it is a Scalable Vector Graphic and should fit within the space of its HTML container, defined by its CSS. One purpose for resizing is to reduce file size when serving, and that would not happen with SVG (except in the absurd, rare case where a bitmap image was put inside an SVG). It should merely accept it as is, and allow the editor user to specify its size attributes for display.

**Comment by rber474** [comment]
I also believe that Plone should support SVG for profile portraits. However, I disagree with letting the user choose the size of the portrait displayed in the author info. This could lead to unexpected layout issues for each user, necessitating overrides of styles or themes. The scale size and format for this feature are currently defined as static settings in `Products.PlonePAS`, with dimensions set to 75x100, anticipating a resizable image through PIL.

In addressing this issue, filtering allowed images should suffice to resolve it. In my opinion, a PLIP (Plone Improvement Proposal) or Enhancement should be initiated to refactor all portrait functionality.

Here are my personal thoughts on this:

- Introduce configuration options in the user option control panel or site control panel, enabling administrators to adjust image dimensions. 
- Correspondingly, modify `Products.PlonePAS/utils.py` to fetch these settings and scale the image accordingly.
- Refactor `Products.PlonePAS membership tool.py/changeMemberPortrait` to verify whether the uploaded file is an `image/svg+xml`, thus avoiding scaling.
- Modify `Products.CMFPlone @@author` view to adapt container attributes based on the configured settings, ensuring consistent aspect ratios across all image types.
- Display the portrait in the `@@personal-information view`.
- Add a small portrait to the `edit-bar toolbar` on the left side, next to the username.

Advanced changes:

- Allow users to adjust the image (position, zoom) after it's uploaded.


What do you think?

**Comment by stevepiercy** [comment]
@rber474 that, sir, is a PLIP worthy proposal.

The only question is in which repo should it be made? I think `CMFPlone` is the default, but it could touch many others as well.

**Comment by rber474** [comment]
@stevepiercy Good question!


- **Products.PlonePAS**:
    - memberdata_tool.py
    - utils.py with the scale_image function
    - config.py with the static settings

- **Products.CMFPlone**:
    - MemberGroup settings controlpanel
    - Author view
 
- **plone.base**:
    - Schema interface for MemberGroup settings

- **plone.app.users**:
    - personal-information view

- **Barceloneta.Theme** (??)
- **mockup and plone.staticresources** if any JS functionality is added (i.e: zoom or position change)



Yeah, a few repositories. 😄 

Products.PlonePAS and ProductsCMFPlone has the most changes to do... For being my first PLIP not bad.
As commented [here](https://github.com/plone/plone.app.users/issues/119#issuecomment-1576385594)  by @mauritsvanrees Products.CMFPlone could include plone.app.users, so I also will go for that repo.

I don't know if it is a way of reference all repositories being affected by a PLIP, if you agree we can create it.

**Comment by stevepiercy** [comment]
I would recommend only one primary repo for a PLIP, and cross-referencing other repos from the primary. Choose the repo in which the greatest amount of work or collaboration is needed. I did that for my [event content type PLIP](https://github.com/plone/volto/issues/5629).
