### ISSUE TITLE
Better 1.x --> 2.x upgrade

### ISSUE THREAD

**Issue by lentinj** [plone/plone.app.users#23]
If you have 1.0-style schema customisations, the upgrade is hella painful thanks to the schema provider component. I bashed through it by:
- Using wildcard.fixpersistentutilities with `FPU_GENERATE_MISSING_CLASSES` to start Plone, and remove the `IUserDataSchemaProvider`.
- pdb-ing through the ZMI components tab to remove it from the component registry. Editing the XML is broken, and sounds like it's been broken for some time. Without doing this GenericSetup falls over.

I guess we need:
- To reinstate `plone.app.users.userdataschema.IUserDataSchemaProvider` with a note that it's just there to get Plone to start during upgrades.
- Either an upgrade step to remove any `IUserDataSchemaProvider` components or a helper to let you do that in your own product.

**Comment by puittenbroek** [comment]
This is all also a problem when uninstalling, I finally managed to accomplish this for our product. 
See code here, I tried everything I could think off, but in the end the low level approach was the only that worked everytime.

https://github.com/collective/collective.smsauthenticator/blob/improved-uninstall/src/collective/smsauthenticator/setuphandlers.py#L110

**Comment by ale-rt** [comment]
I am sorry a fix was not provided for this.
I think now the time for this to be relevant has passed.
If I am wrong please reopen the issue.
