### ISSUE TITLE
Too many groups break "Add new user" form

### ISSUE THREAD

**Issue by alecghica** [plone/plone.app.users#33]
**How to reproduce**

1. login as a Manager
1. create many user groups
1. check "Many groups?" under @@usergroup-controlpanel
1. click "Add new user" under @@usergroup-userprefs

**The issue**

The above steps will make the "Add new user" form to take a huge amount of time to load. This become worst if you use/have many LDAP groups.

**Expected behavior**

When "Many groups?" is checked under @@usergroup-controlpanel it should not list anymore the groups to the "Add new user" form. 

**Suggested solution**

Under ```plone.app.user.browser.register.py``` module hide the groups listing under from the "Add new user" form based on ```portal_properties.site_properties.many_groups``` value.

**Comment by avoinea** [comment]
Fixed.
