### ISSUE TITLE
Unable to save @@personal-preferences when using email as login

### ISSUE THREAD

**Issue by caryan** [plone/plone.app.users#56]
I've got a an issue where if the site uses "email address as login name" users cannot save their personal preferences.  This could be related to this [closed but unsolved issue](https://github.com/plone/Products.CMFPlone/issues/1146). 

Steps to reproduce:

1. Fire up new Plone container: `docker run --rm -p 8080:8080 plone/plone`. This is 5.0.4 right now.
2. Goto  `localhost:8080` and Create a new site
2. Login as `admin:admin` and under "Site Setup -> Security: or `@@security-controlpanel` enable "Use email address as login name"
3.  Create a new user.
4. Log out from admin
5. Login as new user
6. Go to "Preferences"  or `@@personal-preferences` and change "Wysiwyg editor" to "TinyMCE. 
7. Try to "Save"

Throws an error with the traceback in the console:

```shell

2016-04-29T01:51:55 ERROR Zope.SiteErrorLog 1461894715.450.410967712394 http://localhost:8080/Plone/@@personal-preferences
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.app.users.browser.personalpreferences, line 104, in __call__
  Module z3c.form.form, line 233, in __call__
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 145, in update
  Module plone.app.z3cform.csrf, line 21, in execute
  Module z3c.form.action, line 98, in execute
  Module z3c.form.button, line 315, in __call__
  Module z3c.form.button, line 170, in __call__
  Module plone.app.users.browser.account, line 210, in handleSave
  Module plone.app.users.browser.account, line 193, in validate_email
KeyError: 'email'
```

**Comment by mauritsvanrees** [comment]
I hope to have fixed this with the pull request linked above. Waiting for what the test server says.

**Comment by caryan** [comment]
Looks good. Thanks for the quick patch.
